name: Mirror to Public Repository

on:
  push:
    branches:
      - main
      - 'public/*' # make branch visible in public repo
    tags:
      - "*"

jobs:
  mirror:
    name: Mirror Repository
    uses: verygood-ops/cicd-shared/.github/workflows/public-mirror.yaml@public-mirror-workflow-v1.0.0
    secrets: inherit
